alii/search

- worker.js
> feat: add spotify

- worker.js
Add PyPI, Musicstax and the discord.py docs (with alias).
> add more sites

- worker.js
Add the essential websites for any weeb!
> feat: add myanimelist and anilist

- worker.js
> feat: add javadoc

- src/index.ts
1. rust
2. yarn
3. bandcamp
4. soundcloud
Also added comments and classified all the parameters neatly
> better classification + some new sources

- src/index.ts
> add discord (invite) and tweet (twitter web intent)

- package.json
- src/index.ts
- wrangler.toml
- yarn.lock
> new sources

- src/links.ts
added all the amazons, crunchyroll, another ig, & ph 😳
> add: amazons, crunchyroll, ph

- src/links.ts
> feat: add `r/` and `u/` (reddit)

- src/links.ts
> Add odysee.com

- src/links.ts
This PR adds the official Intel specification page.
> add Intel ARK

- src/links.ts
> feat: add arch user repositiory

- src/links.ts
> added know your meme, cheat.sh, and replit

- src/links.ts
added package managers for go, rust, ruby, elixir, and c#
> added more package managers

- src/links.ts
> feat: add pixiv

- src/links.ts
> add translate

- src/links.ts
> feat: add porkbun and mangaupdates

- src/links.ts
> wayback meow :3

- src/links.ts
This PR does the following:
- ~~Makes `!github` actually search~~
- Adds `!gh` alias for GitHub
- Adds `!ddg` alias for DuckDuckGo
- Adds `!tmdb`for TheMovieDB
- Adds `!nebula` for Nebula
- Adds `!thalia` for Thalia (biggest german book store)
- Adds `!sakuta`for Sakuta (one of my own projects; I can remove it again if the site isn't of enough relevance)
- Adds `!animenewsnetwork` & `!ann` for AnimeNewsNetwork
- Adds `!anidb` for AniDB
- Adds `!gmail` for Gmail
> added & tweaked various services

- README.md
- src/links.ts
- wrangler.toml
Added installation instructions
Removed duplicate links
Removed unused values in wrangler.toml
Added who.is link
> Provide installation instructions and fix a few errors

- src/index.ts
- wrangler.toml
> fix: allow special characters in the query

- src/links.ts
This PR adds [Thalia](https://thalia.de), a popular German book store chain.
pls merge i really need this thx
> add thalia
